const constants = {
  EVENTS: {
    ASSET_LOADED: 'EVENTS.ASSET_LOADED',
    ASSETS_LOADED: 'EVENTS.ASSETS_LOADED',
    DOM_MOUSE_SCROLL: 'EVENTS.DOM_MOUSE_SCROLL',
    GO_TO_PROJECT: 'EVENTS.GO_TO_PROJECT',
    MOUSEWHEEL: 'EVENTS.MOUSEWHEEL',
    SCROLL: 'EVENTS.SCROLL',
    SLIDER_VIDEO_CHANGED: 'EVENT.SLIDER_VIDEO_CHANGED',
    RESIZE: 'EVENTS.RESIZE',
  },
};

module.exports = constants;
