const ressources = {
  images: [
    { id: 'logo', url: 'images/imanebahouss-logo-red.png', description: 'logo' },

    { id: 'jeanine-preview', url: 'images/projects/jeanine/imanebahouss-jeanine-preview.png', description: '' },
    { id: 'jeanine-footer', url: 'images/projects/jeanine/imanebahouss-jeanine-footer.png', description: '' },
    { id: 'jeanine1', url: 'images/projects/jeanine/imanebahouss-jeanine-1.png', description: '' },
    { id: 'jeanine3', url: 'images/projects/jeanine/imanebahouss-jeanine-3.png', description: '' },
    { id: 'jeanine4', url: 'images/projects/jeanine/imanebahouss-jeanine-4.png', description: '' },
    { id: 'jeanine5', url: 'images/projects/jeanine/imanebahouss-jeanine-5.png', description: '' },
    { id: 'jeanine6', url: 'images/projects/jeanine/imanebahouss-jeanine-6.png', description: '' },
    { id: 'jeanine7', url: 'images/projects/jeanine/imanebahouss-jeanine-7.png', description: '' },
    { id: 'jeanine8', url: 'images/projects/jeanine/imanebahouss-jeanine-8.png', description: '' },
    { id: 'jeanine9', url: 'images/projects/jeanine/imanebahouss-jeanine-9.png', description: '' },
    { id: 'jeanine10', url: 'images/projects/jeanine/imanebahouss-jeanine-10.png', description: '' },
    { id: 'jeanine11', url: 'images/projects/jeanine/imanebahouss-jeanine-11.png', description: '' },
    { id: 'jeanine12', url: 'images/projects/jeanine/imanebahouss-jeanine-12.png', description: '' },
    { id: 'jeanine13', url: 'images/projects/jeanine/imanebahouss-jeanine-13.png', description: '' },
    { id: 'jeanine14', url: 'images/projects/jeanine/imanebahouss-jeanine-14.png', description: '' },
    { id: 'jeanine15', url: 'images/projects/jeanine/imanebahouss-jeanine-15.png', description: '' },
    { id: 'jeanine16', url: 'images/projects/jeanine/imanebahouss-jeanine-16.png', description: '' },
    { id: 'jeanine17', url: 'images/projects/jeanine/imanebahouss-jeanine-17.png', description: '' },
    { id: 'jeanine18', url: 'images/projects/jeanine/imanebahouss-jeanine-18.png', description: '' },
    { id: 'jeanine19', url: 'images/projects/jeanine/imanebahouss-jeanine-19.png', description: '' },
    { id: 'jeanine20', url: 'images/projects/jeanine/imanebahouss-jeanine-20.gif', description: '' },
    { id: 'jeanine21', url: 'images/projects/jeanine/imanebahouss-jeanine-21.gif', description: '' },
    { id: 'jeanine22', url: 'images/projects/jeanine/imanebahouss-jeanine-22.gif', description: '' },
    { id: 'jeanine23', url: 'images/projects/jeanine/imanebahouss-jeanine-23.gif', description: '' },
    { id: 'jeanine24', url: 'images/projects/jeanine/imanebahouss-jeanine-24.gif', description: '' },
    { id: 'jeanine25', url: 'images/projects/jeanine/imanebahouss-jeanine-25.gif', description: '' },

    { id: 'mathetmalice-preview', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-preview.png', description: '' },
    { id: 'mathetmalice-footer', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-footer.png', description: '' },
    { id: 'mathetmalice1', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-1.jpg', description: '' },
    { id: 'mathetmalice3', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-3.jpg', description: '' },
    { id: 'mathetmalice4', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-4.jpg', description: '' },
    { id: 'mathetmalice5', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-5.jpg', description: '' },
    { id: 'mathetmalice6', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-6.jpg', description: '' },
    { id: 'mathetmalice7', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-7.jpg', description: '' },
    { id: 'mathetmalice8', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-8.jpg', description: '' },
    { id: 'mathetmalice9', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-9.jpg', description: '' },
    { id: 'mathetmalice9bis', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-9.png', description: '' },
    { id: 'mathetmalice10', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-10.png', description: '' },
    { id: 'mathetmalice11', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-11.png', description: '' },
    { id: 'mathetmalice12', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-12.png', description: '' },
    { id: 'mathetmalice13', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-13.png', description: '' },
    { id: 'mathetmalice14', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-14.png', description: '' },
    { id: 'mathetmalice15', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-15.png', description: '' },
    { id: 'mathetmalice16', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-16.png', description: '' },
    { id: 'mathetmalice17', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-17.jpg', description: '' },
    { id: 'mathetmalice180', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-18-0.png', description: '' },
    { id: 'mathetmalice18', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-18.png', description: '' },
    { id: 'mathetmalice19', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-19.png', description: '' },
    { id: 'mathetmalice20', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-20.png', description: '' },
    { id: 'mathetmalice21', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-21.png', description: '' },
    { id: 'mathetmalice22', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-22.png', description: '' },
    { id: 'mathetmalice23', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-23.png', description: '' },
    { id: 'mathetmalice24', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-24.jpg', description: '' },
    { id: 'mathetmalice25', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-25.jpg', description: '' },
    { id: 'mathetmalice26', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-26.jpg', description: '' },
    { id: 'mathetmalice27', url: 'images/projects/mathetmalice/imanebahouss-mathetmalice-27.jpg', description: '' },

    { id: 'sisley-preview', url: 'images/projects/sisley/imanebahouss-sisley-preview.png', description: '' },
    { id: 'sisley-footer', url: 'images/projects/sisley/imanebahouss-sisley-footer.png', description: '' },
    { id: 'sisley1', url: 'images/projects/sisley/imanebahouss-sisley-1.png', description: '' },
    { id: 'sisley3', url: 'images/projects/sisley/imanebahouss-sisley-3.png', description: '' },
    { id: 'sisley4', url: 'images/projects/sisley/imanebahouss-sisley-4.png', description: '' },
    { id: 'sisley5', url: 'images/projects/sisley/imanebahouss-sisley-5.png', description: '' },
    { id: 'sisley6', url: 'images/projects/sisley/imanebahouss-sisley-6.png', description: '' },
    { id: 'sisley7', url: 'images/projects/sisley/imanebahouss-sisley-7.png', description: '' },
    { id: 'sisley8', url: 'images/projects/sisley/imanebahouss-sisley-8.png', description: '' },
    { id: 'sisley9', url: 'images/projects/sisley/imanebahouss-sisley-9.png', description: '' },
    { id: 'sisley10', url: 'images/projects/sisley/imanebahouss-sisley-10.png', description: '' },
    { id: 'sisley11', url: 'images/projects/sisley/imanebahouss-sisley-11.png', description: '' },
    { id: 'sisley12', url: 'images/projects/sisley/imanebahouss-sisley-12.png', description: '' },
    { id: 'sisley13', url: 'images/projects/sisley/imanebahouss-sisley-13.png', description: '' },
    { id: 'sisley14', url: 'images/projects/sisley/imanebahouss-sisley-14.png', description: '' },
    { id: 'sisley15', url: 'images/projects/sisley/imanebahouss-sisley-15.png', description: '' },
    { id: 'sisley16', url: 'images/projects/sisley/imanebahouss-sisley-16.png', description: '' },
    { id: 'sisley17', url: 'images/projects/sisley/imanebahouss-sisley-17.png', description: '' },
    { id: 'sisley18', url: 'images/projects/sisley/imanebahouss-sisley-18.png', description: '' },
    { id: 'sisley19', url: 'images/projects/sisley/imanebahouss-sisley-19.png', description: '' },
    { id: 'sisley20', url: 'images/projects/sisley/imanebahouss-sisley-20.png', description: '' },
    { id: 'sisley21', url: 'images/projects/sisley/imanebahouss-sisley-21.png', description: '' },
    { id: 'sisley22', url: 'images/projects/sisley/imanebahouss-sisley-22.png', description: '' },
    { id: 'sisley23', url: 'images/projects/sisley/imanebahouss-sisley-23.png', description: '' },
    { id: 'sisley24', url: 'images/projects/sisley/imanebahouss-sisley-24.gif', description: '' },
    { id: 'sisley25', url: 'images/projects/sisley/imanebahouss-sisley-25.gif', description: '' },
    { id: 'sisley26', url: 'images/projects/sisley/imanebahouss-sisley-26.gif', description: '' },
    { id: 'sisley27', url: 'images/projects/sisley/imanebahouss-sisley-27.gif', description: '' },

    { id: 'sncf-preview', url: 'images/projects/sncf/imanebahouss-sncf-preview.png', description: '' },
    { id: 'sncf-footer', url: 'images/projects/sncf/imanebahouss-sncf-footer.png', description: '' },
    { id: 'sncf1', url: 'images/projects/sncf/imanebahouss-sncf-1.png', description: '' },
    { id: 'sncf3', url: 'images/projects/sncf/imanebahouss-sncf-3.png', description: '' },
    { id: 'sncf4', url: 'images/projects/sncf/imanebahouss-sncf-4.png', description: '' },
    { id: 'sncf5', url: 'images/projects/sncf/imanebahouss-sncf-5.png', description: '' },
    { id: 'sncf6', url: 'images/projects/sncf/imanebahouss-sncf-6.png', description: '' },
    { id: 'sncf7', url: 'images/projects/sncf/imanebahouss-sncf-7.png', description: '' },
    { id: 'sncf8', url: 'images/projects/sncf/imanebahouss-sncf-8.png', description: '' },
    { id: 'sncf9', url: 'images/projects/sncf/imanebahouss-sncf-9.png', description: '' },
    { id: 'sncf10', url: 'images/projects/sncf/imanebahouss-sncf-10.png', description: '' },
    { id: 'sncf11', url: 'images/projects/sncf/imanebahouss-sncf-11.png', description: '' },
    { id: 'sncf12', url: 'images/projects/sncf/imanebahouss-sncf-12.png', description: '' },
    { id: 'sncf13', url: 'images/projects/sncf/imanebahouss-sncf-13.png', description: '' },
    { id: 'sncf14', url: 'images/projects/sncf/imanebahouss-sncf-14.png', description: '' },
    { id: 'sncf15', url: 'images/projects/sncf/imanebahouss-sncf-15.png', description: '' },
    { id: 'sncf16', url: 'images/projects/sncf/imanebahouss-sncf-16.png', description: '' },
    { id: 'sncf17', url: 'images/projects/sncf/imanebahouss-sncf-17.png', description: '' },
    { id: 'sncf18', url: 'images/projects/sncf/imanebahouss-sncf-18.png', description: '' },
    { id: 'sncf19', url: 'images/projects/sncf/imanebahouss-sncf-19.png', description: '' },
    { id: 'sncf201', url: 'images/projects/sncf/imanebahouss-sncf-20_1.png', description: '' },
    { id: 'sncf202', url: 'images/projects/sncf/imanebahouss-sncf-20_2.png', description: '' },
    { id: 'sncf203', url: 'images/projects/sncf/imanebahouss-sncf-20_3.png', description: '' },
    { id: 'sncf20', url: 'images/projects/sncf/imanebahouss-sncf-20.png', description: '' },
    { id: 'sncf21', url: 'images/projects/sncf/imanebahouss-sncf-21.png', description: '' },
    { id: 'sncf22', url: 'images/projects/sncf/imanebahouss-sncf-22.png', description: '' },
    { id: 'sncf23', url: 'images/projects/sncf/imanebahouss-sncf-23.png', description: '' },
    { id: 'sncf24', url: 'images/projects/sncf/imanebahouss-sncf-24.png', description: '' },
    { id: 'sncf25', url: 'images/projects/sncf/imanebahouss-sncf-25.png', description: '' },
    { id: 'sncf26', url: 'images/projects/sncf/imanebahouss-sncf-26.png', description: '' },
    { id: 'sncf27', url: 'images/projects/sncf/imanebahouss-sncf-27.png', description: '' },
    { id: 'sncf28', url: 'images/projects/sncf/imanebahouss-sncf-28.png', description: '' },
    { id: 'sncf29', url: 'images/projects/sncf/imanebahouss-sncf-29.png', description: '' },
    { id: 'sncf30', url: 'images/projects/sncf/imanebahouss-sncf-30.png', description: '' },
    { id: 'sncf31', url: 'images/projects/sncf/imanebahouss-sncf-31.png', description: '' },
    { id: 'sncf32', url: 'images/projects/sncf/imanebahouss-sncf-32.png', description: '' },
    { id: 'sncf33', url: 'images/projects/sncf/imanebahouss-sncf-33.png', description: '' },
    { id: 'sncf34', url: 'images/projects/sncf/imanebahouss-sncf-34.gif', description: '' },
    { id: 'sncf35', url: 'images/projects/sncf/imanebahouss-sncf-35.gif', description: '' },
  ],
  videos: [
    { id: 'mathetmalice', url: 'videos/editis.mp4' },
    { id: 'mathetmalice-long', url: 'videos/editis-longue.mp4' },
    { id: 'jeanine', url: 'videos/jeanine.mp4' },
    { id: 'jeanine-long', url: 'videos/jeanine.mp4' },
    { id: 'sisley', url: 'videos/sisley.mp4' },
    { id: 'sisley-long', url: 'videos/sisley-longue.mp4' },
    { id: 'sncf', url: 'videos/sncf.mp4' },
    { id: 'sncf-long', url: 'videos/sncf-longue.mp4' },
  ],
};

module.exports = ressources;
